[package]
name = "api"
version = "0.1.0"
authors = ["Dominik Rosser <dominik.rosser@protonmail.ch>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.0", features = ["postgres"] }
dotenv = "0.9.0"

